# Generated by Django 4.1.2 on 2022-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.IntegerField(verbose_name="Follower")),
                ("follows", models.IntegerField(verbose_name="Follows")),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="Created Date"),
                ),
            ],
        ),
    ]
