# Generated by Django 4.1.2 on 2022-10-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ins_app", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=100, verbose_name="Hash Tag")),
                ("count", models.IntegerField(verbose_name="Post Count")),
                ("label", models.CharField(max_length=100, verbose_name="Post Date")),
            ],
        ),
    ]
